import assert from 'node:assert/strict';
import { chmod, mkdtemp, mkdir, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
import { openDatabase, importConversation } from '../app/database.mjs';
import { createServer } from '../app/server.mjs';

process.umask(0o077);
const workspace = process.cwd();
const temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'idealista-ui-'));
const databasePath = path.join(temporaryDirectory, 'applicants.sqlite');
const screenshots = path.join(workspace, '.local', 'verification');
await mkdir(screenshots, { recursive: true, mode: 0o700 });
await chmod(screenshots, 0o700);
const db = openDatabase(databasePath);
const server = createServer(db);

function fixture(id, name, fields, overrides = {}) {
  return {
    id, name, exportedAt: '2026-09-23T10:00:00.000Z', listedDate: '10:00',
    properties: [{ url: overrides.propertyUrl ?? 'https://www.idealista.com/inmueble/13579135/' }],
    integrity: { profile: 'completo', history: 'completo', notes: ['Datos de prueba locales.'] },
    profile: { text: `Perfil de ${name}. ${overrides.profileText ?? ''}`, fields },
    messages: overrides.messages ?? [{ sequence: 1, author: name, direction: 'received', dateLabel: '23 septiembre', time: '10:00', rawText: overrides.message ?? `Mensaje de ${name}` }],
  };
}

const applicants = [
  fixture('101', 'Alba', ['Somos una pareja', 'Hay menores: sí', 'Con mascota', 'Ingresos mensuales del grupo: 2.000 €']),
  fixture('102', 'Bruno', ['1 persona', 'Sin menores', 'Sin mascota', 'Ingreso mensual: 1.000 €'], { message: 'Trabajo en el hospital central.', propertyUrl: 'https://www.idealista.com/inmueble/13579135/' }),
  fixture('103', 'Carmen', ['Somos 3 personas', 'Con mascota', 'Ingresos mensuales del grupo: 3.000 €']),
  fixture('104', 'Diego', ['Somos 4 personas', 'Sin menores', 'Ingreso mensual: 2.000 €'], { profileText: '<script>window.pwned=true</script>', messages: [
    { sequence: 1, author: 'Diego', direction: 'received', dateLabel: '23 septiembre', time: '09:59', rawText: '<img src=x onerror=window.pwned=true> Mensaje seguro' },
    { sequence: 2, author: 'Propietario', direction: 'sent', dateLabel: '23 septiembre', time: '10:00', rawText: 'Respuesta de prueba' },
    { sequence: 3, author: 'Diego', direction: 'received', dateLabel: '23 septiembre', time: '10:00', rawText: 'Mensaje más reciente' },
  ] }),
  fixture('105', 'Elena', [], { profileText: '<b>sin formato HTML</b>' }),
  fixture('106', 'Fabio', ['Somos una pareja', 'Hay menores: sí', 'Sin mascota', 'Ingresos mensuales del grupo: 1.500 €']),
  fixture('107', 'Gema', ['1 persona', 'Ingreso mensual: 0 €']),
  fixture('108', 'Áurelio', ['Somos 10 personas', 'Sin menores', 'Sin mascota', 'Ingresos mensuales del grupo: 4.000 €']),
];
for (const [index, item] of applicants.entries()) importConversation(db, item, `fixture-${item.id}.json`, `2026-09-${String(20 - Math.floor(index / 3)).padStart(2, '0')}`);

await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const address = server.address();
const baseUrl = `http://127.0.0.1:${address.port}`;
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 980 } });
const pageErrors = [];
page.on('pageerror', error => pageErrors.push(error.message));
const legacyPeriodRoute = url => /\/api\/properties\/[^/]+\/periods$/.test(new URL(url).pathname);
await page.route(legacyPeriodRoute, route => route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:'No disponible'})}));
let syncPosts = 0;
const syncPostPaths = [];
const syncPostBodies = [];
let nextSyncPostDelay = 0;
let nextIncrementalEffectiveMode='full';
let failNextNoteSave = false;
let fakeSyncJob = { id: null, state: 'idle', phase: null, startedAt: null, endedAt: null, discovered: 0, candidates: 0, exported: 0, imported: 0, error: null, errorCode: null };
await page.route(url => /\/api\/(?:properties\/[^/]+\/(?:periods\/[^/]+\/)?)?sync$/.test(new URL(url).pathname), async route => {
  const method = route.request().method();
  const path = new URL(route.request().url()).pathname;
  const supportsSyncModes=path.includes('/periods/');
  if (method === 'POST') {
    if(nextSyncPostDelay){const delay=nextSyncPostDelay;nextSyncPostDelay=0;await new Promise(resolve=>setTimeout(resolve,delay));}
    syncPosts++;
    syncPostPaths.push(path);
    const requestBody=JSON.parse(route.request().postData()||'{}');
    syncPostBodies.push(requestBody);
    const target = path.match(/\/api\/properties\/([^/]+)\//)?.[1] ?? null;
    const periodId = path.match(/\/periods\/([^/]+)\/sync$/)?.[1] ?? null;
    const mode=requestBody.mode==='full'?'full':'incremental';
    fakeSyncJob = { ...fakeSyncJob, id: `fake-sync-${syncPosts}`, propertyId:target, periodId, state: 'running', phase: 'discovering', sinceDate: '2026-09-23', startedAt: '2026-09-23T10:01:00.000Z', candidates: 2, exported: 1, error: null,
      ...(supportsSyncModes?{requestedMode:mode,effectiveMode:mode==='full'?'full':nextIncrementalEffectiveMode,examined:0,earlyStopped:false,stopReason:null,unchangedThreshold:5,fullCoverage:false}: {}) };
    await route.fulfill({ status: 202, contentType: 'application/json', body: JSON.stringify({ job: fakeSyncJob }) });
    return;
  }
  await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ job: fakeSyncJob,...(supportsSyncModes?{supportsSyncModes:true}:{}) }) });
});
await page.route(url => /\/api\/(?:properties\/[^/]+\/)?applicants\/(?:chat%3A)?101$/i.test(new URL(url).pathname), async route => {
  if (route.request().method() === 'PATCH' && failNextNoteSave && JSON.parse(route.request().postData() || '{}').notes !== undefined) {
    failNextNoteSave = false;
    await route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ error: 'No se han podido guardar las notas.' }) });
    return;
  }
  await route.continue();
});

async function count(expected) {
  await page.locator('#count').waitFor({ state: 'visible' });
  await page.waitForFunction(value => document.querySelectorAll('#rows tr').length === value, expected);
  assert.equal(await page.locator('#rows tr').count(), expected);
}

async function resetFilters() {
  await page.getByRole('button', { name: 'Limpiar' }).click();
  await count(8);
}

async function choose(id, value, expected) {
  await page.locator(`#${id}`).selectOption(value);
  await count(expected);
}

async function columnValues(key) {
  const column=await page.locator(`th[data-sort="${key}"]`).evaluate(th=>[...th.parentElement.children].filter(cell=>getComputedStyle(cell).display!=='none').indexOf(th)+1);
  return page.locator(`#rows tr td:nth-child(${column})`).evaluateAll(cells => cells.map(cell => cell.innerText.trim()));
}
async function visibleNames(){return page.locator('.person-button').evaluateAll(buttons=>buttons.map(button=>button.textContent.replace(/ \(\d+\)$/,'')));}
async function setRange(id, value) { await page.locator(`#${id}`).evaluate((input, next) => { input.value = next; input.dispatchEvent(new Event('input', { bubbles: true })); }, String(value)); }

try {
  await page.goto(baseUrl, { waitUntil: 'networkidle' });
  await page.getByRole('heading',{name:'Mis viviendas'}).waitFor();
  assert.equal(await page.locator('#workspaceView').isVisible(),false,'home does not expose workspace actions');
  assert.equal(await page.locator('.home-card').count(),1);
  assert.match(await page.locator('.home-card').innerText(),/Piso de prueba.*825,00/s);
  assert.equal(new URL(page.url()).searchParams.has('propertyId'),false);
  await page.locator('.home-card').first().press('Enter');
  await count(8);
  await page.locator('#rentalSince').waitFor();
  await page.locator('#rentalSince').fill('2026-09-23');
  await page.getByRole('button', { name: 'Guardar fecha' }).click();
  await page.getByText('Fecha guardada.').waitFor();
  await page.locator('#name').fill('Alba');await count(1);
  const filteredUrl=page.url(),expandedWidth=await page.locator('.table-wrap').evaluate(node=>node.getBoundingClientRect().width);
  const toggleFilters=page.getByRole('button',{name:'Ocultar filtros'});
  assert.equal(await toggleFilters.getAttribute('aria-controls'),'filterPanel');
  await toggleFilters.click();
  assert.equal(await page.locator('#filterPanel').isHidden(),true,'collapsed panel leaves the layout and tab order');
  assert.equal(await page.getByRole('button',{name:'Mostrar filtros'}).getAttribute('aria-expanded'),'false');
  assert.equal(await page.locator('#name').inputValue(),'Alba','hiding filters retains their values');
  assert.equal(page.url(),filteredUrl,'hiding filters retains URL query');
  assert.equal(await page.locator('#rows tr').count(),1,'hiding filters retains results');
  assert.ok(await page.locator('.table-wrap').evaluate(node=>node.getBoundingClientRect().width)>expandedWidth+100,'table gains panel width on desktop');
  await page.reload({waitUntil:'networkidle'});await count(1);
  assert.equal(await page.locator('#filterPanel').isHidden(),true,'collapsed preference survives reload');
  await page.getByRole('button',{name:'Mostrar filtros'}).press('Enter');
  assert.equal(await page.locator('#filterPanel').isVisible(),true,'keyboard can restore filters');
  assert.equal(await page.locator('#name').inputValue(),'Alba');
  assert.equal(await page.getByRole('button',{name:'Ocultar filtros'}).getAttribute('aria-expanded'),'true');
  assert.ok(Math.abs((await page.locator('.table-wrap').evaluate(node=>node.getBoundingClientRect().width))-expandedWidth)<3,'restored panel shrinks table');
  await page.locator('#name').fill('');await count(8);

  for (const [value, expected] of [['1', 2], ['0', 3], ['unknown', 3]]) {
    await choose('children', value, expected);
    await resetFilters();
  }
  for (const [value, expected] of [['1', 2], ['0', 3], ['unknown', 3]]) {
    await choose('pets', value, expected);
    await resetFilters();
  }

  await page.locator('#peopleMin').fill('2');
  await page.locator('#peopleMax').fill('2');
  await count(2);
  await resetFilters();
  await setRange('incomeMin', 2000);
  await setRange('incomeMax', 2000);
  await count(2);
  await resetFilters();
  await setRange('incomeMin', 0);
  await setRange('incomeMax', 0);
  await count(1);
  assert.match(await page.locator('#rows').innerText(), /Gema/);
  await resetFilters();

  const peopleSort = page.getByRole('button', { name: /Ordenar por Personas/ });
  await peopleSort.click();
  assert.equal(await page.locator('th[data-sort="people_count"]').getAttribute('aria-sort'), 'ascending');
  assert.deepEqual(await columnValues('people_count'), ['1', '1', '2', '2', '3', '4', '10', 'No indicado']);
  assert.equal(await page.locator('#sortSummary').innerText(), 'Personas: de menor a mayor');
  await peopleSort.press('Enter');
  assert.equal(await page.locator('th[data-sort="people_count"]').getAttribute('aria-sort'), 'descending');
  assert.deepEqual(await columnValues('people_count'), ['10', '4', '3', '2', '2', '1', '1', 'No indicado']);
  assert.equal(await page.locator('#sortSummary').innerText(), 'Personas: de mayor a menor');

  await page.getByRole('button', { name: /Ordenar por Interesado/ }).click();
  assert.equal(await page.locator('th[data-sort="name"]').getAttribute('aria-sort'), 'ascending');
  assert.deepEqual(await visibleNames(), ['Alba', 'Áurelio', 'Bruno', 'Carmen', 'Diego', 'Elena', 'Fabio', 'Gema'],'name sort uses names rather than displayed counts');

  await peopleSort.click();
  await peopleSort.press('Enter');
  await choose('children', '0', 3);
  assert.equal(await page.locator('th[data-sort="people_count"]').getAttribute('aria-sort'), 'descending');
  await resetFilters();
  await page.getByRole('button', { name: '↻ Actualizar' }).click();
  await count(8);
  assert.equal(await page.locator('th[data-sort="people_count"]').getAttribute('aria-sort'), 'descending');

  await page.getByRole('button', { name: 'Añadir a favoritos: Alba' }).click();
  await page.getByRole('status').getByText('Guardado en favoritos.').waitFor();
  assert.equal(await page.locator('th[data-sort="people_count"]').getAttribute('aria-sort'), 'descending');
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Quitar de favoritos: Alba' }).waitFor();
  await page.locator('button[data-status="favorites"]').click();
  await count(1);
  assert.match(await page.locator('#rows').innerText(), /Alba/);

  await page.locator('button[data-status="active"]').click();
  await count(8);
  await page.getByRole('button', { name: 'Descartar a Bruno' }).click();
  await page.getByRole('status').getByText('Interesado descartado.').waitFor();
  await count(7);
  assert.doesNotMatch(await page.locator('#rows').innerText(), /Bruno/);
  await page.locator('button[data-status="discarded"]').click();
  await count(1);
  assert.match(await page.locator('#rows').innerText(), /Bruno/);
  await page.reload({ waitUntil: 'networkidle' });
  await count(1);
  await page.getByRole('button', { name: 'Recuperar a Bruno' }).click();
  await page.getByRole('status').getByText('Interesado recuperado.').waitFor();
  await count(0);
  await page.locator('button[data-status="active"]').click();
  await count(8);
  await page.getByRole('button', { name: 'Ver ficha de Diego' }).first().click();
  await page.getByRole('dialog').getByText('<script>window.pwned=true</script>').waitFor();
  assert.equal(await page.locator('#detail script').count(), 0);
  assert.equal(await page.evaluate(() => window.pwned), undefined);
  assert.match(await page.getByRole('dialog').innerText(), /<img src=x onerror=window\.pwned=true> Mensaje seguro/);
  assert.equal(await page.locator('#detail .message').count(), 3, 'the detail keeps the stored message count');
  assert.deepEqual(await page.locator('#detail .message').evaluateAll(messages=>messages.map(message=>({text:message.querySelector('pre').textContent,direction:[...message.classList].find(name=>name==='sent'||name==='received')}))),[
    {text:'Mensaje más reciente',direction:'received'},
    {text:'Respuesta de prueba',direction:'sent'},
    {text:'<img src=x onerror=window.pwned=true> Mensaje seguro',direction:'received'},
  ],'the newest canonical messages, including same-minute ties, render first');
  await page.getByRole('button', { name: 'Cerrar detalle' }).click();

  await page.getByRole('button', { name: 'Ver ficha de Alba' }).first().click();
  const notes = page.locator('#detailNotes');
  await notes.fill('Llamar\npor la tarde');
  await page.getByRole('button', { name: 'Cambiar favorito' }).click();
  assert.equal(await notes.inputValue(), 'Llamar\npor la tarde', 'draft survives a favorite action that reloads detail');
  failNextNoteSave = true;
  await page.getByRole('button', { name: 'Guardar notas' }).click();
  await page.getByText('No se han podido guardar las notas.').waitFor();
  assert.equal(await notes.inputValue(), 'Llamar\npor la tarde', 'failed save retains the note draft');
  await page.getByRole('button', { name: 'Guardar notas' }).click();
  await page.getByText('Notas guardadas.').waitFor();
  await page.getByRole('button', { name: 'Cerrar detalle' }).click();
  await page.getByRole('button', { name: 'Ver ficha de Alba' }).first().click();
  assert.equal(await notes.inputValue(), 'Llamar\npor la tarde', 'unsaved note draft survives reopening');
  await notes.fill('');
  await page.getByRole('button', { name: 'Guardar notas' }).click();
  await page.getByText('Notas guardadas.').waitFor();
  await page.getByRole('button', { name: 'Cerrar detalle' }).click();
  await page.getByRole('button', { name: 'Ver ficha de Alba' }).first().click();
  assert.equal(await notes.inputValue(), '', 'saving an empty note clears it');
  await page.getByRole('button', { name: 'Cerrar detalle' }).click();

  await page.locator('#messageQuery').fill('hospital');
  await count(1);
  assert.match(await page.locator('#rows').innerText(), /Bruno[\s\S]*hospital central/i);
  await page.locator('#messageQuery').fill('');
  await count(8);

  await page.locator('#children').selectOption('0');
  await count(3);
  await peopleSort.click();
  await peopleSort.press('Enter');
  const syncButton = page.locator('#sync');
  assert.equal(await page.locator('#syncFull').isHidden(),true,'older sync API does not expose unsupported full mode');
  await syncButton.click();
  assert.equal(syncPosts, 1, 'one click starts exactly one sync request');
  assert.deepEqual(syncPostBodies.at(-1),{},'older sync API still receives its original empty POST');
  await assert.equal(await syncButton.isDisabled(), true);
  await page.getByText(/Buscando chats nuevos .*Desde 23 de septiembre de 2026 · 2 candidatos · 1 exportado/).waitFor();
  fakeSyncJob = { ...fakeSyncJob, state: 'succeeded', phase: null, endedAt: '2026-09-23T10:02:00.000Z', imported: 0, updated: 0 };
  await page.getByText('Sincronización completada. Desde 23 de septiembre de 2026.').waitFor({ timeout: 2500 });
  await count(3);
  assert.equal(await page.locator('#children').inputValue(), '0');
  assert.equal(await page.locator('th[data-sort="people_count"]').getAttribute('aria-sort'), 'descending');

  fakeSyncJob = { ...fakeSyncJob, id: 'fake-sync-running-after-reload', state: 'running', phase: 'exporting', candidates: 4, exported: 2, imported: 0 };
  const postsBeforeReload = syncPosts;
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByText(/Preparando conversaciones .*Desde 23 de septiembre de 2026 · 4 candidatos · 2 exportados/).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Sincronizando…' }).isDisabled(), true);
  assert.equal(syncPosts, postsBeforeReload, 'reloading adopts a running job without a POST');
  fakeSyncJob = { ...fakeSyncJob, state: 'failed', phase: null, error: 'Chrome necesita que vuelvas a iniciar sesión.' };
  await page.getByText('Chrome necesita que vuelvas a iniciar sesión.').waitFor({ timeout: 2500 });
  assert.equal(await page.getByRole('button', { name: 'Sincronizar datos desde Idealista' }).isDisabled(), false);
  await resetFilters();

  await page.locator('#toast').waitFor({ state: 'hidden' });
  await page.screenshot({ path: path.join(screenshots, 'desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload({ waitUntil: 'networkidle' });
  await count(8);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'mobile viewport has horizontal page overflow');
  await page.screenshot({ path: path.join(screenshots, 'mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 980 });
  fakeSyncJob = { ...fakeSyncJob, id: null, propertyId: null, state: 'idle', phase: null, error: null };
  await page.reload({ waitUntil: 'networkidle' });
  await count(8);
  const originalPropertyId = await page.locator('#propertySelect').inputValue();
  await page.getByRole('button', { name: 'Añadir vivienda' }).click();
  await page.locator('#newPropertyForm [name="title"]').fill('Piso Olivar');
  await page.locator('#newPropertyForm [name="address"]').fill('Calle Olivar 12');
  await page.locator('#newPropertyForm [name="monthlyRent"]').fill('900.50');
  await page.locator('#newPropertyForm [name="rentalSince"]').fill('2026-09-23');
  await page.getByRole('button', { name: 'Guardar vivienda' }).click();
  await page.locator('#propertyDialog').waitFor({ state: 'hidden' });
  const olivarId = await page.locator('#propertySelect').inputValue();
  assert.notEqual(olivarId, originalPropertyId);
  await count(0);
  assert.match(await page.locator('#propertyTitle').innerText(), /Piso Olivar/);
  assert.match(await page.locator('#propertyAddress').innerText(), /900,50/);
  assert.equal(await page.locator('#sync').isDisabled(), true);
  assert.equal(await page.locator('#syncFull').isDisabled(), true,'full sync is unavailable without a listing URL');
  assert.match(await page.locator('#syncHelper').innerText(), /Añade la URL de Idealista/);

  await page.getByRole('button', { name: 'Añadir interesado' }).click();
  const manualForm = page.locator('#newApplicantForm');
  await manualForm.locator('[name="name"]').fill('Luisa Manual');
  await manualForm.locator('[name="phone"]').fill('600123456');
  await manualForm.locator('[name="email"]').fill('luisa@example.test');
  await manualForm.locator('[name="peopleCount"]').fill('2');
  await manualForm.locator('[name="hasChildren"]').selectOption('1');
  await manualForm.locator('[name="hasPets"]').selectOption('0');
  await manualForm.locator('[name="monthlyIncome"]').fill('1250.50');
  await manualForm.locator('[name="incomeScope"]').selectOption('grupo');
  await manualForm.locator('[name="notes"]').fill('Visita el viernes');
  await page.getByRole('button', { name: 'Guardar interesado' }).click();
  await page.locator('#applicantDialog').waitFor({ state: 'hidden', timeout: 3000 }).catch(async()=>{throw new Error(`Manual form error: ${await manualForm.locator('.form-error').innerText()}`);});
  await count(1);
  assert.match(await page.locator('#rows').innerText(), /Luisa Manual[\s\S]*Añadido manualmente[\s\S]*1\.?250,50/);
  await page.getByRole('button', { name: 'Ver ficha de Luisa Manual' }).click();
  await page.getByText('Interesado añadido manualmente').waitFor();
  assert.match(await page.locator('#detail').innerText(), /Interesado añadido manualmente[\s\S]*600123456[\s\S]*luisa@example.test/);
  assert.doesNotMatch(await page.locator('#detail').innerText(), /Conversación ·/);
  assert.equal(await page.locator('#detailNotes').inputValue(), 'Visita el viernes');
  await page.locator('#detailNotes').fill('Visita confirmada');
  await page.getByRole('button', { name: 'Guardar notas' }).click();
  await page.getByText('Notas guardadas.').waitFor();
  await page.getByRole('button', { name: 'Cambiar favorito' }).click();
  await page.getByRole('button', { name: 'Cerrar detalle' }).click();
  await page.locator('button[data-status="favorites"]').click();
  await count(1);
  await page.getByRole('button', { name: 'Descartar a Luisa Manual' }).click();
  await page.locator('button[data-status="discarded"]').click();
  await count(1);
  await page.getByRole('button', { name: 'Recuperar a Luisa Manual' }).click();
  await page.locator('button[data-status="active"]').click();
  await count(1);
  await page.locator('#name').fill('Luisa');await count(1);
  await page.locator('#name').fill('Alba');await count(0);
  await page.getByRole('button', { name: 'Limpiar' }).click();await count(1);
  await setRange('incomeMin',1250);await setRange('incomeMax',1300);await count(1);
  await page.getByRole('button', { name: 'Limpiar' }).click();await count(1);

  await page.getByRole('button', { name: 'Editar vivienda' }).click();
  const editHousing = page.locator('#newPropertyForm');
  assert.equal(await editHousing.locator('[name="title"]').inputValue(), 'Piso Olivar');
  assert.equal(await editHousing.locator('[name="monthlyRent"]').inputValue(), '900.5');
  await editHousing.locator('[name="title"]').fill('Piso Olivar renovado');
  await editHousing.locator('[name="address"]').fill('Calle Olivar 14');
  await editHousing.locator('[name="monthlyRent"]').fill('950.75');
  await editHousing.locator('[name="rentalSince"]').fill('2026-09-24');
  await editHousing.locator('[name="idealistaUrl"]').fill('https://www.idealista.com/inmueble/87654321/');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.locator('#propertyDialog').waitFor({ state: 'hidden' });
  await count(1);
  assert.equal(await page.locator('#propertySelect').inputValue(), olivarId);
  assert.match(await page.locator('#propertyTitle').innerText(), /Piso Olivar renovado/);
  assert.match(await page.locator('#propertyAddress').innerText(), /Calle Olivar 14[\s\S]*950,75/);
  assert.equal(await page.locator('#rentalSince').inputValue(), '2026-09-24');
  assert.equal(await page.locator('#sync').isDisabled(), false);
  await page.reload({ waitUntil: 'networkidle' });
  await count(1);
  assert.equal(await page.locator('#propertySelect').inputValue(), olivarId);
  assert.match(await page.locator('#propertyTitle').innerText(), /Piso Olivar renovado/);
  await page.getByRole('button', { name: 'Ver ficha de Luisa Manual' }).click();
  await page.locator('#detailNotes').waitFor();
  assert.equal(await page.locator('#detailNotes').inputValue(), 'Visita confirmada');
  await page.getByRole('button', { name: 'Cerrar detalle' }).click();
  await page.getByRole('button', { name: 'Editar vivienda' }).click();
  assert.equal(await editHousing.locator('[name="idealistaUrl"]').isEditable(), true);
  await page.getByRole('button', { name: 'Cerrar vivienda' }).click();

  await page.getByRole('button', { name: 'Añadir vivienda' }).click();
  await page.locator('#newPropertyForm [name="title"]').fill('Ático Río');
  await page.locator('#newPropertyForm [name="rentalSince"]').fill('2026-09-23');
  await page.locator('#newPropertyForm [name="idealistaUrl"]').fill('https://www.idealista.com/inmueble/12345678/');
  await page.getByRole('button', { name: 'Guardar vivienda' }).click();
  await page.locator('#propertyDialog').waitFor({ state: 'hidden' });
  const rioId = await page.locator('#propertySelect').inputValue();
  assert.notEqual(rioId, olivarId);
  await count(0);
  assert.equal(await page.locator('#sync').isDisabled(), false);
  await page.locator('#propertySelect').selectOption(olivarId);await count(1);
  await page.getByRole('button', { name: 'Ver ficha de Luisa Manual' }).click();
  await page.locator('#propertySelect').selectOption(originalPropertyId);
  await count(8);
  assert.equal(await page.locator('#detail').evaluate(dialog=>dialog.open), false);
  assert.equal(await page.locator('#favoriteCount').innerText(), '0');
  await page.locator('#propertySelect').selectOption(rioId);await count(0);
  assert.match(await page.locator('#propertyTitle').innerText(), /Ático Río/);
  assert.match(new URL(page.url()).searchParams.get('propertyId'), new RegExp(rioId));

  fakeSyncJob = { ...fakeSyncJob, id: 'running-olivar', propertyId: olivarId, state: 'running', phase: 'exporting', sinceDate: '2026-09-23', candidates: 3, exported: 1 };
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByText(/Preparando conversaciones · Piso Olivar/).waitFor();
  assert.equal(await page.locator('#sync').isDisabled(), true);
  fakeSyncJob = { ...fakeSyncJob, state: 'failed', phase: null, error: 'Prueba terminada' };
  await page.getByText('Prueba terminada').waitFor({ timeout: 2500 });
  nextSyncPostDelay = 250;
  const syncResponse = page.waitForResponse(response => response.request().method()==='POST' && /\/sync$/.test(new URL(response.url()).pathname));
  await page.locator('#sync').click();
  const posted = await syncResponse;
  assert.equal(new URL(posted.url()).pathname, `/api/properties/${rioId}/sync`);
  assert.equal(syncPostPaths.at(-1), `/api/properties/${rioId}/sync`);
  assert.equal(fakeSyncJob.propertyId, rioId);
  fakeSyncJob = { ...fakeSyncJob, state: 'failed', phase: null, error: 'Prueba terminada' };
  await page.getByText('Prueba terminada').waitFor({ timeout: 2500 });

  await page.route(url => new URL(url).pathname === `/api/properties/${olivarId}`, async route => {
    await new Promise(resolve => setTimeout(resolve, 400));
    await route.continue();
  });
  await page.locator('#propertySelect').selectOption(olivarId);
  await page.locator('#propertySelect').selectOption(rioId);
  await count(0);
  await page.waitForTimeout(500);
  assert.match(await page.locator('#propertyTitle').innerText(), /Ático Río/, 'late Olivar response cannot overwrite Río');
  assert.equal(new URL(page.url()).searchParams.get('propertyId'), rioId);

  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload({ waitUntil: 'networkidle' });
  await count(0);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'mobile multi-property UI overflows');
  await page.getByRole('button', { name: 'Editar vivienda' }).click();
  assert.equal(await page.locator('#propertyDialog').evaluate(dialog=>dialog.scrollWidth<=dialog.clientWidth), true, 'mobile housing form overflows');
  await page.getByRole('button', { name: 'Cerrar vivienda' }).click();
  await page.getByRole('button', { name: 'Añadir interesado' }).click();
  assert.equal(await page.locator('#applicantDialog').evaluate(dialog=>dialog.scrollWidth<=dialog.clientWidth), true, 'mobile interested form overflows');
  await page.locator('#applicantDialog [data-close]').click();
  await page.unroute(legacyPeriodRoute);
  fakeSyncJob = { ...fakeSyncJob, id:null, periodId:null, propertyId:null, state:'idle', phase:null, error:null };
  await page.setViewportSize({ width:1440, height:980 });
  await page.goto(`${baseUrl}/?propertyId=${originalPropertyId}`, { waitUntil:'networkidle' });
  await count(8);
  await page.locator('#periodControls').waitFor({ state:'visible' });
  const originalPeriodId=await page.locator('#periodSelect').inputValue();
  assert.equal(new URL(page.url()).searchParams.get('periodId'),originalPeriodId);
  assert.match(await page.locator('#periodSummary').innerText(), /Búsqueda activa.*825,00/);
  const realSyncCapability=await fetch(`${baseUrl}/api/properties/${originalPropertyId}/periods/${encodeURIComponent(originalPeriodId)}/sync`).then(response=>response.json());
  assert.equal(realSyncCapability.supportsSyncModes,true,'isolated backend advertises the real sync-mode capability');
  await page.locator('#syncFull').waitFor({state:'visible'});
  const scopedSyncPath=`/api/properties/${originalPropertyId}/periods/${encodeURIComponent(originalPeriodId)}/sync`;
  await page.locator('#sync').click();
  assert.equal(syncPostPaths.at(-1),scopedSyncPath);
  assert.deepEqual(syncPostBodies.at(-1),{},'main sync requests the backward-compatible default mode');
  assert.equal(fakeSyncJob.requestedMode,'incremental');
  assert.equal(fakeSyncJob.effectiveMode,'full','first incremental request can perform a complete baseline');
  assert.equal(await page.locator('#syncFull').isDisabled(),true,'full mode cannot start while another job runs');
  fakeSyncJob={...fakeSyncJob,state:'succeeded',phase:null,examined:8,candidates:8,fullCoverage:true,imported:1,updated:2,newIncomingApplicants:1,newIncomingMessages:2};
  await page.getByText(/Revisión completa finalizada.*8 revisiones de chat.*8 candidatos en el listado.*1 nueva importada.*2 historiales actualizados.*1 interesado con mensajes recibidos nuevos.*2 mensajes recibidos nuevos/).waitFor({timeout:2500});
  assert.equal(await page.locator('#syncFull').isDisabled(),false);
  nextIncrementalEffectiveMode='incremental';
  await page.locator('#sync').click();
  assert.deepEqual(syncPostBodies.at(-1),{},'later main sync still uses the default request');
  fakeSyncJob={...fakeSyncJob,examined:7,candidates:20,exported:4,unchangedStreak:5};
  await page.getByText(/7 revisiones de chat · 20 candidatos en el listado/).waitFor({timeout:2500});
  fakeSyncJob={...fakeSyncJob,state:'succeeded',phase:null,earlyStopped:true,stopReason:'unchanged_streak',fullCoverage:false,imported:0,updated:0,newIncomingApplicants:0,newIncomingMessages:0};
  await page.getByText(/Revisión rápida finalizada.*7 revisiones de chat.*20 candidatos en el listado.*Detenido tras 5 chats consecutivos sin novedades/).waitFor({timeout:2500});
  assert.doesNotMatch(await page.locator('#syncStatus').innerText(),/Sincronización completada/,'early stop does not claim full coverage');
  await page.locator('#syncFull').click();
  assert.deepEqual(syncPostBodies.at(-1),{mode:'full'},'explicit full action sends the full mode');
  const postsWhileFullRunning=syncPosts;
  assert.equal(await page.locator('#sync').isDisabled(),true);
  assert.equal(await page.locator('#syncFull').isDisabled(),true);
  await page.locator('#syncFull').evaluate(button=>button.click());
  assert.equal(syncPosts,postsWhileFullRunning,'disabled control cannot duplicate a running sync');
  await page.locator('#propertySelect').selectOption(rioId);await count(0);
  await page.locator('#syncFull').waitFor({state:'visible'});
  assert.equal(await page.locator('#sync').isDisabled(),true,'global running job blocks another housing');
  assert.equal(await page.locator('#syncFull').isDisabled(),true,'full mode shares the global running guard');
  await page.locator('#propertySelect').selectOption(originalPropertyId);await count(8);
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('#sync').isDisabled(),true,'reload adopts the existing job');
  assert.equal(await page.locator('#syncFull').isDisabled(),true);
  fakeSyncJob={...fakeSyncJob,state:'failed',phase:null,error:'No se pudo completar la revisión completa.'};
  await page.getByText('No se pudo completar la revisión completa.').waitFor({timeout:2500});
  assert.equal(await page.locator('#syncFull').isDisabled(),false,'failure restores the full action');
  await page.locator('#syncFull').click();
  assert.deepEqual(syncPostBodies.at(-1),{mode:'full'});
  fakeSyncJob={...fakeSyncJob,state:'succeeded',phase:null,examined:22,candidates:20,fullCoverage:true,earlyStopped:false,stopReason:null,error:null,imported:0,updated:0};
  await page.getByText(/Revisión completa finalizada.*22 revisiones de chat.*20 candidatos en el listado/).waitFor({timeout:2500});
  const receivedOnly=await page.evaluate(async ({propertyId,periodId})=>{const result=await fetch(`/api/properties/${propertyId}/periods/${periodId}/applicants?status=all`).then(r=>r.json());return result.items.find(item=>item.name==='Alba');},{propertyId:originalPropertyId,periodId:originalPeriodId});
  assert.equal(receivedOnly.hasReplied,false,'real received-only chat has no owner reply');
  assert.equal(receivedOnly.awaitingReply,null,'undated legacy message cannot assert a pending turn');
  assert.equal(receivedOnly.messageCount,1,'original period counts its stored chat message');
  const receivedOnlyDetail=await page.evaluate(async ({propertyId,periodId,applicantId})=>fetch(`/api/properties/${propertyId}/periods/${periodId}/applicants/${encodeURIComponent(applicantId)}`).then(r=>r.json()),{propertyId:originalPropertyId,periodId:originalPeriodId,applicantId:receivedOnly.applicant_id});
  assert.equal(receivedOnly.messageCount,receivedOnlyDetail.messages.length,'list count matches stored detail history');
  const attentionStates={101:{syncAttention:'message',newIncomingCount:2,attentionRevision:'r1'},102:{syncAttention:'new',newIncomingCount:1,attentionRevision:'b1'}};
  const replyFixture={101:true,102:false,103:null,104:true,105:true,107:true};
  const pendingFixture={101:true,102:true,103:null,104:false,105:false,106:null,107:false,108:null};
  const messageCountFixture={101:2,102:10,103:0,104:1,105:null,106:null,107:null,108:null};
  const arrivalFixture={101:{arrivalDate:'2026-09-23',arrivalAt:'2026-09-23T08:00:00.000Z'},102:{arrivalDate:'2026-09-23',arrivalAt:'2026-09-23T09:00:00.000Z'},103:{arrivalDate:'2026-09-23',arrivalAt:null},104:{arrivalDate:'2026-09-24',arrivalAt:'2026-09-24T08:00:00.000Z'},105:{arrivalDate:'2026-09-22',arrivalAt:'2026-09-22T08:00:00.000Z'},106:{arrivalDate:null,arrivalAt:null},107:{arrivalDate:'2026-09-23',arrivalAt:'2026-09-23T08:00:00.000Z'},108:{arrivalDate:null,arrivalAt:null}};
  const attentionAcks=[];
  let failAttentionDetail=true,staleAttentionAck=true,delayAttentionDetail=false;
  const attentionPath=url=>new URL(url).pathname.startsWith(`/api/properties/${originalPropertyId}/periods/${encodeURIComponent(originalPeriodId)}/applicants`);
  await page.route(attentionPath,async route=>{
    const request=route.request(),pathname=new URL(request.url()).pathname,method=request.method();
    if(pathname.endsWith('/attention/read')){
      const id=decodeURIComponent(pathname.split('/').at(-3)).replace(/^chat:/,''),revision=JSON.parse(request.postData()).revision;
      attentionAcks.push({id,revision});
      if(id==='101'&&staleAttentionAck){staleAttentionAck=false;attentionStates[101]={syncAttention:'message',newIncomingCount:3,attentionRevision:'r2'};await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'Hay mensajes nuevos',...attentionStates[101]})});return;}
      attentionStates[id]={syncAttention:null,newIncomingCount:0,attentionRevision:null};
      await route.fulfill({contentType:'application/json',body:JSON.stringify(attentionStates[id])});return;
    }
    if(method!=='GET'){await route.continue();return;}
    const id=pathname.split('/').at(-1)==='applicants'?null:decodeURIComponent(pathname.split('/').at(-1)).replace(/^chat:/,'');
    if(id==='101'&&failAttentionDetail){failAttentionDetail=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Detalle temporalmente no disponible'})});return;}
    if(id==='101'&&delayAttentionDetail)await new Promise(resolve=>setTimeout(resolve,400));
    const response=await route.fetch(),body=await response.json();
    if(id)Object.assign(body,attentionStates[id]||{syncAttention:null,newIncomingCount:0,attentionRevision:null},arrivalFixture[id],{hasReplied:Object.hasOwn(replyFixture,id)?replyFixture[id]:null,awaitingReply:pendingFixture[id],messageCount:messageCountFixture[id]});
    else for(const item of body.items){const external=String(item.conversation_id).split(':').at(-1);Object.assign(item,attentionStates[external]||{syncAttention:null,newIncomingCount:0,attentionRevision:null},arrivalFixture[external],{hasReplied:Object.hasOwn(replyFixture,external)?replyFixture[external]:null,awaitingReply:pendingFixture[external],messageCount:messageCountFixture[external]});}
    await route.fulfill({response,body:JSON.stringify(body)});
  });
  await page.getByRole('button',{name:'↻ Actualizar'}).click();
  await page.locator('#rows tr[data-id="chat:101"] .attention-badge').getByText('Nuevo mensaje (2)').waitFor();
  await page.locator('#rows tr[data-id="chat:102"] .attention-badge').getByText('Nuevo').waitFor();
  await page.locator('th[data-sort="arrivalDate"]').waitFor({state:'visible'});
  await page.locator('#replyHeading').waitFor({state:'visible'});
  await page.locator('#pendingReplyHeading').waitFor({state:'visible'});
  assert.equal(await page.locator('#messageCountHeading').count(),0,'message count has no standalone column');
  await page.locator('#replyFilter').waitFor({state:'visible'});
  await page.locator('#pendingReplyFilter').waitFor({state:'visible'});
  assert.match(await page.locator('#rows tr[data-id="chat:101"] .reply-status').innerText(),/Has respondido/);
  assert.equal(await page.locator('#rows tr[data-id="chat:102"] .reply-status').innerText(),'Sin respuesta');
  assert.equal(await page.locator('#rows tr[data-id="chat:103"] .reply-status').innerText(),'No confirmado');
  assert.match(await page.locator('#rows tr[data-id="chat:101"] .pending-status').innerText(),/Pendiente de responder/);
  assert.equal(await page.locator('#rows tr[data-id="chat:104"] .pending-status').innerText(),'Esperando respuesta');
  assert.equal(await page.locator('#rows tr[data-id="chat:103"] .pending-status').innerText(),'No confirmado');
  assert.equal(await page.locator('#rows tr[data-id="chat:101"] .person-button').innerText(),'Alba (2)');
  assert.equal(await page.locator('#rows tr[data-id="chat:103"] .person-button').innerText(),'Carmen (0)');
  assert.equal(await page.locator('#rows tr[data-id="chat:105"] .person-button').innerText(),'Elena','missing count is omitted rather than shown as zero');
  assert.equal(await page.locator('#rows tr[data-id="chat:101"] .person-button').getAttribute('aria-label'),'Ver ficha de Alba, 2 mensajes');
  assert.equal(await page.locator('#rows tr[data-id="chat:101"] .reply-status').getAttribute('title'),'Hay al menos un mensaje tuyo en este periodo');
  assert.match(await page.locator('#rows tr[data-id="chat:101"] .arrival-date').innerText(),/23.*10:00/);
  assert.match(await page.locator('#rows tr[data-id="chat:101"] .person-meta').innerText(),/Última actividad:/);
  assert.match(await page.locator('#rows tr[data-id="chat:106"]').innerText(),/No indicada/);
  const arrivalSort=page.getByRole('button',{name:/Ordenar por Fecha de llegada/});
  await arrivalSort.click();
  assert.equal(await page.locator('th[data-sort="arrivalDate"]').getAttribute('aria-sort'),'ascending');
  assert.deepEqual(await visibleNames(),['Elena','Alba','Gema','Bruno','Carmen','Diego','Fabio','Áurelio']);
  assert.equal(await page.locator('#sortSummary').innerText(),'Fecha de llegada: más antiguos primero');
  await arrivalSort.press('Enter');
  assert.equal(await page.locator('th[data-sort="arrivalDate"]').getAttribute('aria-sort'),'descending');
  assert.deepEqual(await visibleNames(),['Diego','Bruno','Alba','Gema','Carmen','Elena','Fabio','Áurelio']);
  assert.equal(await page.locator('#sortSummary').innerText(),'Fecha de llegada: más recientes primero');
  const replySort=page.getByRole('button',{name:/Ordenar por Respuesta/});
  await replySort.click();
  assert.equal(await page.locator('#replyHeading').getAttribute('aria-sort'),'ascending');
  assert.deepEqual((await columnValues('hasReplied')).slice(0,5),['✓ Has respondido','✓ Has respondido','✓ Has respondido','✓ Has respondido','Sin respuesta']);
  assert.deepEqual((await columnValues('hasReplied')).slice(5),['No confirmado','No confirmado','No confirmado']);
  await replySort.press('Enter');
  assert.equal(await page.locator('#replyHeading').getAttribute('aria-sort'),'descending');
  assert.equal((await columnValues('hasReplied'))[0],'Sin respuesta');
  assert.deepEqual((await columnValues('hasReplied')).slice(5),['No confirmado','No confirmado','No confirmado']);
  const pendingSort=page.getByRole('button',{name:/Ordenar por Seguimiento/});
  await pendingSort.click();
  assert.equal(await page.locator('#pendingReplyHeading').getAttribute('aria-sort'),'ascending');
  assert.deepEqual((await columnValues('awaitingReply')).slice(0,5),['↩ Pendiente de responder','↩ Pendiente de responder','Esperando respuesta','Esperando respuesta','Esperando respuesta']);
  assert.deepEqual((await columnValues('awaitingReply')).slice(5),['No confirmado','No confirmado','No confirmado']);
  await pendingSort.press('Enter');
  assert.equal(await page.locator('#pendingReplyHeading').getAttribute('aria-sort'),'descending');
  assert.deepEqual((await columnValues('awaitingReply')).slice(0,3),['Esperando respuesta','Esperando respuesta','Esperando respuesta']);
  assert.deepEqual((await columnValues('awaitingReply')).slice(5),['No confirmado','No confirmado','No confirmado']);
  assert.equal(await page.getByRole('button',{name:/Ordenar por Mensajes/}).count(),0,'removed count cannot be sorted');
  assert.equal(await page.locator('#rows tr.attention-row').count(),2,'outgoing/profile/no-op rows have no attention marker');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'attention and reply columns overflow at 390px');
  const mobileTableTop=await page.locator('.table-wrap').evaluate(node=>node.getBoundingClientRect().top);
  await page.getByRole('button',{name:'Ocultar filtros'}).click();
  assert.equal(await page.locator('#filterPanel').isHidden(),true);
  assert.ok((await page.locator('.table-wrap').evaluate(node=>node.getBoundingClientRect().top))<mobileTableTop,'hiding filters gives the mobile table more vertical space');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'collapsed filters overflow at 390px');
  await page.getByRole('button',{name:'Mostrar filtros'}).click();
  await page.setViewportSize({width:1440,height:980});
  await page.getByRole('button',{name:/Ordenar por Interesado/}).click();
  await page.locator('#name').fill('Alba');await count(1);
  await page.getByRole('button',{name:'Ver ficha de Alba'}).click();
  await page.getByText('Detalle temporalmente no disponible').waitFor();
  assert.equal(attentionAcks.length,0,'failed detail fetch cannot acknowledge marker');
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  await page.getByRole('button',{name:'Ver ficha de Alba'}).click();
  await page.locator('#detailBody .attention-notice').waitFor();
  assert.deepEqual(attentionAcks,[{id:'101',revision:'r1'}]);
  await page.locator('#rows tr[data-id="chat:101"] .attention-badge').getByText('Nuevo mensaje (3)').waitFor();
  assert.match(await page.locator('#rows tr[data-id="chat:101"] .pending-status').innerText(),/Pendiente de responder/,'attention ACK does not clear pending reply');
  assert.equal(await page.locator('#name').inputValue(),'Alba','attention refresh preserves name filter');
  assert.equal(await page.locator('th[data-sort="name"]').getAttribute('aria-sort'),'ascending','attention refresh preserves sort');
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  await page.getByRole('button',{name:'Ver ficha de Alba'}).click();
  await page.waitForFunction(()=>document.querySelector('#rows tr[data-id="chat:101"] .attention-badge')===null);
  assert.deepEqual(attentionAcks.at(-1),{id:'101',revision:'r2'});
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  await page.locator('#name').fill('');await count(8);
  await page.getByRole('button',{name:'Ver ficha de Bruno'}).click();
  await page.waitForFunction(()=>document.querySelector('#rows tr[data-id="chat:102"] .attention-badge')===null);
  assert.deepEqual(attentionAcks.at(-1),{id:'102',revision:'b1'});
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  attentionStates[101]={syncAttention:'message',newIncomingCount:1,attentionRevision:'r3'};
  await page.getByRole('button',{name:'↻ Actualizar'}).click();
  await page.locator('#rows tr[data-id="chat:101"] .attention-badge').getByText('Nuevo mensaje').waitFor();
  delayAttentionDetail=true;
  await page.getByRole('button',{name:'Ver ficha de Alba'}).click();
  await page.locator('#propertySelect').selectOption(olivarId);
  await count(1);
  await page.waitForTimeout(500);
  assert.equal(attentionAcks.length,3,'stale detail response after housing switch cannot ACK');
  assert.equal(await page.locator('.attention-badge').count(),0,'attention does not leak across housing');
  delayAttentionDetail=false;
  await page.locator('#propertySelect').selectOption(originalPropertyId);
  await count(8);
  await page.unroute(attentionPath);
  await page.goto(`${baseUrl}/?propertyId=${originalPropertyId}&periodId=${originalPeriodId}&sort=messageCount`,{waitUntil:'networkidle'});
  await count(8);
  assert.equal(new URL(page.url()).searchParams.has('sort'),false,'old count-sort bookmark falls back to default sorting');
  assert.equal(await page.locator('#sortSummary').innerText(),'Actividad más reciente primero');
  assert.equal(await page.locator('#newPeriod').isVisible(),false,'cannot open a second search while one is open');
  await page.getByRole('button',{name:'Editar vivienda'}).click();
  assert.equal(await page.locator('#newPropertyForm [name="monthlyRent"]').isVisible(),false,'housing edit contains stable fields only');
  await page.getByRole('button',{name:'Cerrar vivienda'}).click();
  await page.getByRole('button',{name:'Editar búsqueda'}).click();
  assert.equal(await page.locator('#periodForm [name="monthlyRent"]').inputValue(),'825');
  await page.locator('#periodForm [data-close]').click();
  const invalidClose=await page.evaluate(async ({propertyId,periodId})=>{const response=await fetch(`/api/properties/${propertyId}/periods/${periodId}/close`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chosenApplicantId:'manual:not-a-real-person'})});return response.status;},{propertyId:originalPropertyId,periodId:originalPeriodId});
  assert.equal(invalidClose,400,'cannot close by choosing an applicant outside the search');
  await page.getByRole('button',{name:'Ver ficha de Alba'}).click();
  await page.locator('#detailNotes').fill('Nota histórica conservada');
  await page.getByRole('button',{name:'Guardar notas'}).click();
  await page.getByText('Notas guardadas.').waitFor();
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  await page.getByRole('button',{name:'Ver ficha de Bruno'}).click();
  await page.getByRole('button',{name:/Elegir a Bruno y cerrar búsqueda/}).click();
  await page.locator('#closePeriodReview').getByText(/Bruno/).waitFor();
  await page.getByRole('button',{name:'Confirmar cierre'}).click();
  await page.locator('#closePeriodDialog').waitFor({state:'hidden'});
  assert.match(await page.locator('#periodSummary').innerText(),/Búsqueda cerrada.*Bruno/);
  assert.equal(await page.locator('#addApplicant').isVisible(),false);
  assert.equal(await page.locator('#editPeriod').isVisible(),false);
  assert.equal(await page.locator('#sync').isDisabled(),true);
  assert.equal(await page.locator('#syncFull').isDisabled(),true,'closed search cannot start a full sync');
  assert.equal(await page.getByRole('button',{name:/Descartar a Alba/}).count(),0);
  assert.equal(await page.getByRole('button',{name:/Añadir a favoritos: Alba/}).count(),0);
  await page.getByRole('button',{name:'Ver ficha de Alba'}).click();
  await page.locator('#detailBody').getByText('Nota histórica conservada').waitFor();
  assert.match(await page.locator('#detailBody').innerText(),/Nota histórica conservada/);
  assert.equal(await page.locator('#detailNotes').count(),0);
  assert.equal(await page.getByRole('button',{name:'Guardar notas'}).count(),0);
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  await page.getByRole('button',{name:'Nueva búsqueda'}).click();
  assert.equal(await page.locator('#periodForm [name="monthlyRent"]').inputValue(),'825');
  assert.match(await page.locator('#periodForm [name="idealistaUrl"]').inputValue(),/13579135/);
  assert.equal(await page.locator('#periodForm [name="rentalSince"]').inputValue(),'2026-09-24');
  await page.locator('#periodForm [name="monthlyRent"]').fill('875');
  await page.getByRole('button',{name:'Crear búsqueda'}).click();
  await page.locator('#periodDialog').waitFor({state:'hidden'});
  await count(0);
  const newPeriodId=await page.locator('#periodSelect').inputValue();
  assert.notEqual(newPeriodId,originalPeriodId);
  assert.equal(new URL(page.url()).searchParams.get('periodId'),newPeriodId);
  assert.match(await page.locator('#periodSummary').innerText(),/Búsqueda activa.*875,00/);
  assert.equal(await page.locator('#sync').isDisabled(),false,'reused listing is available for the new search');
  const reusedChat=fixture('101','Alba',['1 persona'],{message:'Conversación nueva de septiembre'});
  reusedChat.activityDate='2026-09-24';
  reusedChat.messages[0].messageDate='2026-09-24';
  reusedChat.messages[0].text=reusedChat.messages[0].rawText;
  reusedChat.messages[0].occurredAt=new Date(Math.ceil(Date.now()/60000)*60000+60000).toISOString();
  reusedChat.messages[0].time=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(reusedChat.messages[0].occurredAt));
  reusedChat.messages.push({...reusedChat.messages[0],sequence:2,author:'Propietario',direction:'sent',rawText:'Respuesta del propietario',text:'Respuesta del propietario'});
  reusedChat.messages[0].dateLabel='24 septiembre';
  reusedChat.exportedAt='2026-09-24T11:00:00.000Z';
  importConversation(db,reusedChat,'new-period-101.json','2026-09-24',originalPropertyId,newPeriodId);
  await page.getByRole('button',{name:'↻ Actualizar'}).click();
  await count(1);
  const realArrival=await page.evaluate(async ({propertyId,periodId})=>{const result=await fetch(`/api/properties/${propertyId}/periods/${periodId}/applicants?status=all`).then(r=>r.json());return result.items.find(item=>item.name==='Alba');},{propertyId:originalPropertyId,periodId:newPeriodId});
  assert.equal(realArrival.arrivalDate,'2026-09-24','real imported arrival uses received message date');
  assert.equal(realArrival.arrivalAt,reusedChat.messages[0].occurredAt,'real imported arrival uses received message time');
  assert.equal(realArrival.hasReplied,true,'real owner message in this period is reflected in the list');
  assert.equal(realArrival.awaitingReply,false,'real latest owner message means waiting for a reply');
  assert.equal(realArrival.messageCount,2,'reused external chat has a separate new-period message count');
  const reusedDetail=await page.evaluate(async ({propertyId,periodId,applicantId})=>fetch(`/api/properties/${propertyId}/periods/${periodId}/applicants/${encodeURIComponent(applicantId)}`).then(r=>r.json()),{propertyId:originalPropertyId,periodId:newPeriodId,applicantId:realArrival.applicant_id});
  assert.equal(realArrival.messageCount,reusedDetail.messages.length,'new-period list count matches its stored detail');
  assert.equal(await page.locator('#rows tr[data-id="'+realArrival.applicant_id+'"] .person-button').innerText(),'Alba (2)');
  assert.match(await page.locator('#rows tr[data-id="'+realArrival.applicant_id+'"] .arrival-date').innerText(),/24.*2026/);
  assert.match(await page.locator('#rows tr[data-id="'+realArrival.applicant_id+'"] .reply-status').innerText(),/Has respondido/);
  assert.equal(await page.locator('#rows tr[data-id="'+realArrival.applicant_id+'"] .pending-status').innerText(),'Esperando respuesta');
  await page.getByRole('button',{name:'Ver ficha de Alba'}).click();
  await page.locator('#detailBody').getByText(/Conversación nueva de septiembre/).waitFor();
  assert.match(await page.locator('#detailBody').innerText(),/Conversación nueva de septiembre/);
  assert.equal(await page.locator('#detailNotes').inputValue(),'','a reused chat starts with separate notes');
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  await page.getByRole('button',{name:'Añadir interesado'}).click();
  await page.locator('#newApplicantForm [name="name"]').fill('Nueva inquilina');
  await page.locator('#newApplicantForm [name="notes"]').fill('Solo búsqueda nueva');
  await page.getByRole('button',{name:'Guardar interesado'}).click();
  await page.locator('#applicantDialog').waitFor({state:'hidden'});
  await count(2);
  const manualArrival=await page.evaluate(async ({propertyId,periodId})=>{const result=await fetch(`/api/properties/${propertyId}/periods/${periodId}/applicants?status=all`).then(r=>r.json());return result.items.find(item=>item.name==='Nueva inquilina');},{propertyId:originalPropertyId,periodId:newPeriodId});
  assert.match(manualArrival.arrivalDate,/^2026-09-24$/,'manual arrival has fixed creation day');
  assert.match(manualArrival.arrivalAt,/^2026-09-24T/,'manual arrival has creation instant');
  assert.equal(manualArrival.hasReplied,null,'manual applicant has no chat reply state');
  assert.equal(manualArrival.awaitingReply,null,'manual applicant has no pending chat turn');
  assert.equal(manualArrival.messageCount,0,'manual applicant has zero stored chat messages');
  assert.equal(await page.locator('#rows tr[data-id="'+manualArrival.applicant_id+'"] .reply-status').innerText(),'Sin chat');
  assert.equal(await page.locator('#rows tr[data-id="'+manualArrival.applicant_id+'"] .pending-status').innerText(),'Sin chat');
  assert.equal(await page.locator('#rows tr[data-id="'+manualArrival.applicant_id+'"] .person-button').innerText(),'Nueva inquilina (0)');
  await choose('pendingReply','no',1);
  await page.waitForFunction(()=>new URL(location.href).searchParams.get('pendingReply')==='no');
  assert.match(await page.locator('#rows').innerText(),/Alba/);
  await choose('pendingReply','',2);
  reusedChat.messages.push({...reusedChat.messages[0],sequence:3,author:'Alba',direction:'received',rawText:'Una pregunta más',text:'Una pregunta más'});
  reusedChat.exportedAt='2026-09-24T11:01:00.000Z';
  importConversation(db,reusedChat,'new-period-101-update.json','2026-09-24',originalPropertyId,newPeriodId);
  await page.getByRole('button',{name:'↻ Actualizar'}).click();
  await page.locator('#rows tr[data-id="'+realArrival.applicant_id+'"] .pending-status').getByText(/Pendiente de responder/).waitFor();
  const latestTurn=await page.evaluate(async ({propertyId,periodId})=>{const result=await fetch(`/api/properties/${propertyId}/periods/${periodId}/applicants?status=all`).then(r=>r.json());return result.items.find(item=>item.name==='Alba');},{propertyId:originalPropertyId,periodId:newPeriodId});
  assert.equal(latestTurn.hasReplied,true,'earlier owner reply remains true after new incoming message');
  assert.equal(latestTurn.awaitingReply,true,'new incoming turn makes the same chat pending');
  assert.equal(latestTurn.messageCount,3,'refreshed history updates the new-period message count');
  assert.equal(await page.locator('#rows tr[data-id="'+realArrival.applicant_id+'"] .person-button').innerText(),'Alba (3)');
  await choose('reply','replied',1);
  assert.equal(new URL(page.url()).searchParams.get('reply'),'replied');
  await choose('pendingReply','yes',1);
  await page.waitForFunction(()=>new URL(location.href).searchParams.get('pendingReply')==='yes');
  assert.match(await page.locator('#rows').innerText(),/Alba/,'server combines reply and pending filters');
  await page.reload({waitUntil:'networkidle'});
  await count(1);
  assert.equal(await page.locator('#reply').inputValue(),'replied','reply filter bookmark survives reload');
  assert.equal(await page.locator('#pendingReply').inputValue(),'yes','pending reply filter bookmark survives reload');
  await choose('pendingReply','no',0);
  await choose('reply','not_replied',0);
  await choose('pendingReply','',0);
  await choose('reply','no_chat',1);
  await choose('pendingReply','no_chat',1);
  assert.match(await page.locator('#rows').innerText(),/Nueva inquilina/);
  await choose('reply','unknown',0);
  await choose('pendingReply','unknown',0);
  await page.getByRole('button',{name:'Limpiar'}).click();
  await count(2);
  assert.equal(new URL(page.url()).searchParams.has('reply'),false,'reset removes reply filter from URL');
  assert.equal(new URL(page.url()).searchParams.has('pendingReply'),false,'reset removes pending filter from URL');
  await page.reload({waitUntil:'networkidle'});
  await count(2);
  assert.equal(await page.locator('#periodSelect').inputValue(),newPeriodId);
  await page.locator('#periodSelect').selectOption(originalPeriodId);
  await count(8);
  assert.match(await page.locator('#periodSummary').innerText(),/Búsqueda cerrada.*Bruno/);
  assert.doesNotMatch(await page.locator('#rows').innerText(),/Nueva inquilina/);
  await page.reload({waitUntil:'networkidle'});
  await count(8);
  assert.equal(await page.locator('#periodSelect').inputValue(),originalPeriodId,'closed search bookmark survives reload');
  assert.equal(await page.locator('#addApplicant').isVisible(),false,'reload does not reopen archive editing');
  await page.locator('#periodSelect').selectOption(newPeriodId);
  await count(2);
  assert.match(await page.locator('#rows').innerText(),/Nueva inquilina/);
  const delayedArchive=url=>new URL(url).pathname===`/api/properties/${originalPropertyId}/periods/${originalPeriodId}/applicants`;
  await page.route(delayedArchive,async route=>{await new Promise(resolve=>setTimeout(resolve,400));await route.continue();});
  await page.locator('#periodSelect').selectOption(originalPeriodId);
  await page.locator('#periodSelect').selectOption(newPeriodId);
  await count(2);
  await page.waitForTimeout(500);
  assert.match(await page.locator('#rows').innerText(),/Nueva inquilina/,'late archive response cannot replace active search');
  assert.equal(new URL(page.url()).searchParams.get('periodId'),newPeriodId);
  await page.unroute(delayedArchive);
  await page.setViewportSize({width:390,height:844});
  await page.reload({waitUntil:'networkidle'});
  await count(2);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'period UI overflows at 390px');
  await page.getByRole('button',{name:'Editar búsqueda'}).click();
  assert.equal(await page.locator('#periodDialog').evaluate(dialog=>dialog.scrollWidth<=dialog.clientWidth),true);
  await page.locator('#periodDialog [data-close]').click();
  await page.getByRole('button',{name:'Editar vivienda'}).click();
  const housingForm=page.locator('#newPropertyForm');
  assert.equal(await housingForm.locator('[name="idealistaUrl"]').isVisible(),true);
  assert.equal(await housingForm.locator('[name="idealistaUrl"]').isEditable(),true,'imported chats do not lock the housing URL');
  await housingForm.locator('[name="idealistaUrl"]').fill('https://www.idealista.com/inmueble/99999999/');
  let rejectUrlOnce=true;
  const busyUrl=url=>new URL(url).pathname===`/api/properties/${originalPropertyId}`;
  await page.route(busyUrl,async route=>{if(route.request().method()==='PATCH'&&rejectUrlOnce){rejectUrlOnce=false;await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'Sincronización en curso'})});}else await route.continue();});
  await page.getByRole('button',{name:'Guardar cambios'}).click();
  await housingForm.getByText('Sincronización en curso').waitFor();
  assert.equal(await housingForm.locator('[name="idealistaUrl"]').inputValue(),'https://www.idealista.com/inmueble/99999999/','failed URL save preserves form');
  await page.getByRole('button',{name:'Guardar cambios'}).click();
  await page.locator('#propertyDialog').waitFor({state:'hidden'});
  await page.unroute(busyUrl);
  await count(2);
  const urlsAfterEdit=await page.evaluate(async ({propertyId,oldPeriodId,newPeriodId})=>{const [oldPeriod,newPeriod,house]=await Promise.all([fetch(`/api/properties/${propertyId}/periods/${oldPeriodId}`).then(r=>r.json()),fetch(`/api/properties/${propertyId}/periods/${newPeriodId}`).then(r=>r.json()),fetch(`/api/properties/${propertyId}`).then(r=>r.json())]);return {old:oldPeriod.period.url,current:newPeriod.period.url,defaultUrl:house.property.defaultIdealistaUrl};},{propertyId:originalPropertyId,oldPeriodId:originalPeriodId,newPeriodId});
  assert.match(urlsAfterEdit.old,/13579135/,'closed listing snapshot remains unchanged');
  assert.match(urlsAfterEdit.current,/99999999/);
  assert.match(urlsAfterEdit.defaultUrl,/99999999/);
  await page.getByRole('button',{name:'Ver ficha de Nueva inquilina'}).click();
  await page.getByRole('button',{name:/Elegir a Nueva inquilina y cerrar búsqueda/}).click();
  await page.getByRole('button',{name:'Confirmar cierre'}).click();
  await page.locator('#closePeriodDialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Editar vivienda'}).click();
  await housingForm.locator('[name="idealistaUrl"]').fill('');
  await page.getByRole('button',{name:'Guardar cambios'}).click();
  await page.locator('#propertyDialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Nueva búsqueda'}).click();
  assert.equal(await page.locator('#periodForm [name="idealistaUrl"]').inputValue(),'','cleared default does not reuse archived listing');
  await page.getByRole('button',{name:'Crear búsqueda'}).click();
  await page.locator('#periodDialog').waitFor({state:'hidden'});
  await count(0);
  assert.equal(await page.locator('#sync').isDisabled(),true);
  const homeRequests=[];
  page.on('request',request=>{if(new URL(request.url()).pathname.includes('/applicants'))homeRequests.push(request.url());});
  await page.getByRole('link',{name:'Inicio de Morada · Mis viviendas'}).click();
  await page.getByRole('heading',{name:'Mis viviendas'}).waitFor();
  assert.equal(await page.locator('.home-card').count(),3,'overview lists each housing');
  assert.equal(homeRequests.length,0,'home does not fetch applicants');
  assert.equal(await page.locator('#workspaceView').isVisible(),false);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'home overflows at 390px');
  const rioCard=page.locator('.home-card').filter({hasText:'Ático Río'});
  assert.match(await rioCard.innerText(),/Dirección no indicada/);
  assert.doesNotMatch(await rioCard.innerText(),/Ferrocarril|Olivar/);
  await rioCard.click();
  await count(0);
  assert.equal(new URL(page.url()).searchParams.get('propertyId'),rioId);
  assert.match(await page.locator('#propertyTitle').innerText(),/Ático Río/);
  await page.goBack({waitUntil:'networkidle'});
  await page.getByRole('heading',{name:'Mis viviendas'}).waitFor();
  assert.equal(new URL(page.url()).searchParams.has('propertyId'),false,'browser back returns to overview');
  await page.getByRole('button',{name:'Añadir vivienda'}).click();
  await page.locator('#newPropertyForm [name="title"]').fill('Casa Centro');
  await page.locator('#newPropertyForm [name="monthlyRent"]').fill('650');
  await page.locator('#newPropertyForm [name="rentalSince"]').fill('2026-09-24');
  await page.getByRole('button',{name:'Guardar vivienda'}).click();
  await page.locator('#propertyDialog').waitFor({state:'hidden'});
  await page.locator('#propertyTitle').getByText(/Casa Centro/).waitFor();
  await count(0);
  const centroId=new URL(page.url()).searchParams.get('propertyId');
  assert.ok(centroId&&centroId!==rioId);
  await page.getByRole('link',{name:'Inicio de Morada · Mis viviendas'}).click();
  await page.getByRole('heading',{name:'Mis viviendas'}).waitFor();
  assert.equal(await page.locator('.home-card').count(),4);
  assert.match(await page.locator('.home-card').filter({hasText:'Casa Centro'}).innerText(),/650,00/);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  await page.getByRole('button',{name:'Lista'}).click();
  assert.equal(await page.locator('#homeProperties').getAttribute('data-view'),'list');
  assert.equal(await page.getByRole('button',{name:'Lista'}).getAttribute('aria-pressed'),'true');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'list view overflows at 390px');
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('#homeProperties').getAttribute('data-view'),'list','home view preference survives reload');
  await page.getByRole('button',{name:'Cuadrícula'}).click();
  assert.equal(await page.locator('#homeProperties').getAttribute('data-view'),'grid');
  assert.equal(await page.getByRole('button',{name:'Eliminadas'}).isVisible(),true);
  await page.locator('.home-card').filter({hasText:'Casa Centro'}).click();
  await count(0);
  await page.getByRole('button',{name:'Añadir interesado'}).click();
  await page.locator('#newApplicantForm [name="name"]').fill('Persona Centro');
  await page.locator('#newApplicantForm [name="notes"]').fill('Dato privado recuperable');
  await page.getByRole('button',{name:'Guardar interesado'}).click();
  await page.locator('#applicantDialog').waitFor({state:'hidden'});
  await count(1);
  await page.getByRole('button',{name:'Editar vivienda'}).click();
  assert.equal(await page.locator('#deleteProperty').isVisible(),true);
  await page.locator('#deleteProperty').click();
  await page.locator('#deletePropertyReview').getByText(/Casa Centro/).waitFor();
  assert.match(await page.locator('#deletePropertyDialog').innerText(),/Podrás recuperarlos/);
  await page.locator('#deletePropertyDialog').getByRole('button',{name:'Cancelar',exact:true}).click();
  assert.equal(await page.locator('#deletePropertyDialog').evaluate(dialog=>dialog.open),false,'cancel leaves housing intact');
  await page.locator('#deleteProperty').click();
  let rejectDeleteOnce=true;
  const deleteCentro=url=>new URL(url).pathname===`/api/properties/${centroId}`;
  await page.route(deleteCentro,async route=>{if(route.request().method()==='DELETE'&&rejectDeleteOnce){rejectDeleteOnce=false;await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'Sincronización activa'})});}else await route.continue();});
  await page.locator('#confirmDeleteProperty').click();
  await page.locator('#deletePropertyDialog').getByText('Sincronización activa').waitFor();
  assert.equal(await page.locator('#deletePropertyDialog').evaluate(dialog=>dialog.open),true);
  await page.locator('#confirmDeleteProperty').click();
  await page.unroute(deleteCentro);
  await page.getByRole('heading',{name:'Mis viviendas'}).waitFor();
  assert.equal(await page.locator('.home-card').count(),3);
  await page.getByRole('button',{name:'Eliminadas'}).click();
  await page.locator('.home-card').filter({hasText:'Casa Centro'}).waitFor();
  assert.equal(await page.locator('.home-card').filter({hasText:'Casa Centro'}).locator('a').count(),0,'deleted housing cannot open workspace');
  let rejectRestoreOnce=true;
  const restoreCentro=url=>new URL(url).pathname===`/api/properties/${centroId}/restore`;
  await page.route(restoreCentro,async route=>{if(route.request().method()==='POST'&&rejectRestoreOnce){rejectRestoreOnce=false;await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'Anuncio ya utilizado'})});}else await route.continue();});
  await page.getByRole('button',{name:'Restaurar Casa Centro'}).click();
  await page.locator('#homeError').getByText('Anuncio ya utilizado').waitFor();
  assert.equal(await page.locator('.home-card').count(),1,'restore failure retains deleted item');
  await page.getByRole('button',{name:'Restaurar Casa Centro'}).click();
  await page.unroute(restoreCentro);
  await page.getByRole('button',{name:'Activas'}).waitFor();
  await page.waitForFunction(()=>document.querySelector('#homeActive')?.getAttribute('aria-pressed')==='true'&&document.querySelectorAll('.home-card').length===4);
  await page.locator('.home-card').filter({hasText:'Casa Centro'}).click();
  await count(1);
  await page.getByRole('button',{name:'Ver ficha de Persona Centro'}).click();
  await page.locator('#detailNotes').waitFor();
  assert.equal(await page.locator('#detailNotes').inputValue(),'Dato privado recuperable');
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  await page.getByRole('button',{name:'Editar vivienda'}).click();
  await page.locator('#deleteProperty').click();
  await page.locator('#confirmDeleteProperty').click();
  await page.getByRole('heading',{name:'Mis viviendas'}).waitFor();
  await page.getByRole('button',{name:'Eliminadas'}).click();
  await page.locator('.home-card').filter({hasText:'Casa Centro'}).waitFor();
  await page.getByRole('button',{name:'Eliminar definitivamente Casa Centro'}).click();
  await page.locator('#purgePropertyDialog').getByText(/Persona|conversaciones y notas/).waitFor();
  assert.match(await page.locator('#purgePropertyDialog').innerText(),/copias de seguridad y exportaciones previas no se modifican/i);
  await page.locator('#purgePropertyDialog').getByRole('button',{name:'Cancelar',exact:true}).click();
  assert.equal(await page.locator('.home-card').count(),1,'purge cancel preserves deleted housing');
  await page.getByRole('button',{name:'Eliminar definitivamente Casa Centro'}).click();
  let rejectPurgeOnce=true;
  const purgeCentro=url=>new URL(url).pathname===`/api/properties/${centroId}/permanent`;
  await page.route(purgeCentro,async route=>{if(route.request().method()==='DELETE'&&rejectPurgeOnce){rejectPurgeOnce=false;await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'No se ha podido eliminar'})});}else await route.continue();});
  await page.locator('#confirmPurgeProperty').click();
  await page.locator('#purgePropertyDialog').getByText('No se ha podido eliminar').waitFor();
  assert.equal(await page.locator('#purgePropertyDialog').evaluate(dialog=>dialog.open),true);
  await page.locator('#confirmPurgeProperty').click();
  await page.unroute(purgeCentro);
  await page.getByText('No hay viviendas eliminadas.').waitFor();
  assert.equal(await page.locator('.home-card').count(),0);
  const purgedStatus=await page.evaluate(async id=>(await fetch(`/api/properties/${id}`)).status,centroId);
  assert.equal(purgedStatus,404);
  await page.getByRole('button',{name:'Activas'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.home-card').length===3);
  assert.match(await page.locator('.home-card').first().innerText(),/Piso de prueba|Piso Olivar|Ático Río/);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'active overview overflows after deletion');
  const statePage=await browser.newPage({viewport:{width:390,height:844}});
  let homeMode='empty';
  await statePage.route(url=>new URL(url).pathname==='/api/properties',route=>route.fulfill(homeMode==='empty'?{contentType:'application/json',body:JSON.stringify({properties:[]})}:{status:503,contentType:'application/json',body:JSON.stringify({error:'Temporalmente no disponible'})}));
  await statePage.goto(baseUrl,{waitUntil:'networkidle'});
  await statePage.getByText('Aún no hay viviendas. Añade la primera para empezar.').waitFor();
  assert.equal(await statePage.locator('.home-card').count(),0);
  homeMode='error';
  await statePage.reload({waitUntil:'networkidle'});
  await statePage.getByText(/Temporalmente no disponible/).waitFor();
  assert.equal(await statePage.getByRole('button',{name:'Reintentar'}).isVisible(),true);
  homeMode='empty';
  await statePage.getByRole('button',{name:'Reintentar'}).click();
  await statePage.getByText('Aún no hay viviendas. Añade la primera para empezar.').waitFor();
  await statePage.close();
  assert.deepEqual(pageErrors, [], 'the main interface has no JavaScript errors during the synthetic flow');
  console.log('UI verification passed: housing home, grid/list, URL edits, deletion/restore/purge, periods, attention markers/ACK races, archive, isolation, reload, and 390px layout.');
} finally {
  await browser.close();
  await new Promise(resolve => server.close(resolve));
  db.close();
  await rm(temporaryDirectory, { recursive: true, force: true });
}
