// Explicit public asset list shared by the capture tool and the build.
export const documentationScenes = [
  ['viviendas', 'Viviendas', 'Mis viviendas en cuadrícula'],
  ['viviendas-lista', 'Viviendas', 'Mis viviendas en lista'],
  ['vivienda-nueva', 'Viviendas', 'Añadir vivienda'],
  ['vivienda-editar', 'Viviendas', 'Editar vivienda'],
  ['vivienda-eliminar', 'Viviendas', 'Confirmar eliminación recuperable'],
  ['viviendas-eliminadas', 'Viviendas', 'Viviendas eliminadas y restauración'],
  ['vivienda-borrar', 'Viviendas', 'Confirmar eliminación definitiva'],
  ['interesados', 'Interesados', 'Interesados, filtros y atención a mensajes'],
  ['favoritos', 'Interesados', 'Favoritos'],
  ['descartados', 'Interesados', 'Descartados'],
  ['sin-resultados', 'Interesados', 'Búsqueda sin resultados'],
  ['ficha', 'Interesados', 'Ficha, notas privadas y visitas'],
  ['conversacion', 'Interesados', 'Conversación con mensajes enviados y recibidos'],
  ['interesado-nuevo', 'Interesados', 'Añadir un interesado manualmente'],
  ['busqueda-editar', 'Búsquedas', 'Editar la búsqueda activa'],
  ['busqueda-cerrar', 'Búsquedas', 'Elegir inquilino y cerrar la búsqueda'],
  ['busqueda-cerrada', 'Búsquedas', 'Búsqueda cerrada con inquilino elegido'],
  ['busqueda-reabrir', 'Búsquedas', 'Reabrir conservando los interesados'],
  ['busqueda-nueva', 'Búsquedas', 'Iniciar una nueva búsqueda'],
  ['busqueda-vacia', 'Búsquedas', 'Búsqueda nueva sin interesados, con histórico disponible'],
  ['calendario', 'Visitas', 'Calendario mensual y agenda del día'],
  ['calendario-canceladas', 'Visitas', 'Historial de visitas canceladas'],
  ['visita-nueva', 'Visitas', 'Programar visita y consultar disponibilidad'],
  ['visita-editar', 'Visitas', 'Reprogramar una visita'],
  ['visita-conflicto', 'Visitas', 'Confirmar un solapamiento de visitas'],
  ['sincronizacion-opciones', 'Sincronización', 'Opciones de sincronización'],
  ['sincronizacion-avisos', 'Sincronización', 'Resultado con chats sin anuncio verificable (simulado)'],
  ['sincronizacion-error', 'Sincronización', 'Error de lectura de Chrome (simulado)'],
  ['movil-viviendas', 'Móvil', 'Mis viviendas en móvil'],
  ['movil-interesados', 'Móvil', 'Interesados en móvil'],
  ['movil-calendario', 'Móvil', 'Calendario en móvil'],
];
